"""instruments

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 02:02:51.974026

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not emit sequences.
    op.execute(sa.schema.CreateSequence(sa.Sequence("instrument_uid_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("instrument_uid", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "instrument_type",
            sa.Enum(
                "WEIGHING_SCALE",
                "WEIGHBRIDGE",
                "WEIGHT",
                "FUEL_DISPENSER",
                "MEASURE_LENGTH",
                "MEASURE_VOLUME",
                "OTHER",
                name="instrument_type",
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "capacity_unit",
            sa.Enum("mg", "g", "kg", "t", "mL", "L", "kL", "mm", "cm", "m", name="capacity_unit"),
            nullable=False,
        ),
        sa.Column(
            "accuracy_class",
            sa.Enum("I", "II", "III", "IIII", name="accuracy_class"),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("state_code", sa.Text(), nullable=False),
        sa.Column("district_code", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)", name=op.f("ck_instruments_lat_lng_pair")
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_instruments_capacity_positive")),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90", name=op.f("ck_instruments_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_instruments_longitude_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_instruments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_instruments_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("instrument_uid", name=op.f("uq_instruments_instrument_uid")),
    )
    op.create_index(
        "ix_instruments_mfr_serial",
        "instruments",
        [sa.literal_column("lower(manufacturer)"), "serial_number"],
        unique=True,
    )
    op.create_index(
        "ix_instruments_org_created", "instruments", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_instruments_region", "instruments", ["state_code", "district_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_instruments_region", table_name="instruments")
    op.drop_index("ix_instruments_org_created", table_name="instruments")
    op.drop_index("ix_instruments_mfr_serial", table_name="instruments")
    op.drop_table("instruments")
    # ### end Alembic commands ###
    # Hand-written: autogenerate drops neither the sequence nor the enum types.
    op.execute(sa.schema.DropSequence(sa.Sequence("instrument_uid_seq")))
    for enum_name in ("accuracy_class", "capacity_unit", "instrument_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
