"""applications

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 02:53:37.500275

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not emit sequences.
    op.execute(sa.schema.CreateSequence(sa.Sequence("application_number_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("application_number", sa.Text(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "application_type",
            sa.Enum("VERIFICATION", "RE_VERIFICATION", name="application_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "DOCUMENT_REVIEW",
                "SCHEDULED",
                "INSPECTION",
                "APPROVED",
                "REJECTED",
                "CERTIFICATE_ISSUED",
                name="application_status",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("state_code", sa.Text(), nullable=False),
        sa.Column("district_code", sa.Text(), nullable=False),
        sa.Column("business_notes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_applications_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_applications_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_applications_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("application_number", name=op.f("uq_applications_application_number")),
    )
    op.create_index(
        op.f("ix_applications_instrument_id"), "applications", ["instrument_id"], unique=False
    )
    op.create_index(
        "ix_applications_org_created",
        "applications",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_applications_region_status",
        "applications",
        ["state_code", "district_code", "status"],
        unique=False,
    )
    op.create_index(
        "ux_applications_active_instrument",
        "applications",
        ["instrument_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('REJECTED', 'CERTIFICATE_ISSUED')"),
    )
    op.create_table(
        "application_status_history",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "DOCUMENT_REVIEW",
                "SCHEDULED",
                "INSPECTION",
                "APPROVED",
                "REJECTED",
                "CERTIFICATE_ISSUED",
                name="application_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "DOCUMENT_REVIEW",
                "SCHEDULED",
                "INSPECTION",
                "APPROVED",
                "REJECTED",
                "CERTIFICATE_ISSUED",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_application_status_history_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_status_history_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_status_history")),
    )
    op.create_index(
        op.f("ix_application_status_history_application_id"),
        "application_status_history",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "PROOF_OF_OWNERSHIP",
                "INSTRUMENT_PHOTO",
                "PREVIOUS_CERTIFICATE",
                "MODEL_APPROVAL",
                "OTHER",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_bytes BETWEEN 1 AND 10485760", name=op.f("ck_documents_size_range")
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_documents_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_documents_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("storage_path", name=op.f("uq_documents_storage_path")),
    )
    op.create_index(
        op.f("ix_documents_application_id"), "documents", ["application_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_application_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        op.f("ix_application_status_history_application_id"),
        table_name="application_status_history",
    )
    op.drop_table("application_status_history")
    op.drop_index(
        "ux_applications_active_instrument",
        table_name="applications",
        postgresql_where=sa.text("status NOT IN ('REJECTED', 'CERTIFICATE_ISSUED')"),
    )
    op.drop_index("ix_applications_region_status", table_name="applications")
    op.drop_index("ix_applications_org_created", table_name="applications")
    op.drop_index(op.f("ix_applications_instrument_id"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
    # Hand-written: autogenerate drops neither the sequence nor the enum types.
    op.execute(sa.schema.DropSequence(sa.Sequence("application_number_seq")))
    for enum_name in ("document_type", "application_status", "application_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
