"""inspection checklist

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 10:50:24.145122

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not diff enum *values*, only enum existence. Adding a
    # value to an existing type is its own statement — Postgres has no "ADD VALUE IF NOT
    # EXISTS" transactional guarantee before PG12, but this repo targets a recent Postgres
    # (Supabase), so this is safe inside the migration's transaction as long as the new value
    # is never *used* (e.g. inserted) within this same transaction.
    # IF NOT EXISTS: the value survives `downgrade -1` (Postgres can't drop a single enum
    # value, see downgrade() below), so a repeat `upgrade head` must not fail on it.
    op.execute("ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'INSPECTION_EVIDENCE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_checklist_items",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("item_key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("result", sa.Enum("PASS", "FAIL", "NA", name="checklist_result"), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_checklist_items_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_checklist_items")),
        sa.UniqueConstraint(
            "inspection_id", "item_key", name=op.f("uq_inspection_checklist_items_inspection_id")
        ),
    )
    op.create_table(
        "inspection_measurements",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_measurements_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_measurements")),
        sa.UniqueConstraint(
            "inspection_id", "label", name=op.f("uq_inspection_measurements_inspection_id")
        ),
    )
    op.add_column("inspections", sa.Column("overall_remarks", sa.Text(), nullable=True))
    op.add_column(
        "inspections", sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("inspections", sa.Column("submitted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_inspections_submitted_by_users"),
        "inspections",
        "users",
        ["submitted_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_inspections_submitted_by_users"), "inspections", type_="foreignkey")
    op.drop_column("inspections", "submitted_by")
    op.drop_column("inspections", "submitted_at")
    op.drop_column("inspections", "overall_remarks")
    op.drop_table("inspection_measurements")
    op.drop_table("inspection_checklist_items")
    # ### end Alembic commands ###
    # Hand-written: autogenerate drops neither enum type.
    sa.Enum(name="checklist_result").drop(op.get_bind(), checkfirst=True)
    # Postgres cannot drop a single enum value (no ALTER TYPE ... DROP VALUE). Recreating
    # document_type without INSPECTION_EVIDENCE would require rewriting every dependent column
    # and is out of scope for an MVP downgrade path: the value is left in place. This means
    # `downgrade -1` after this revision does not fully reverse the document_type change —
    # documented here and in backend/CLAUDE.md rather than silently accepted.
