"""certificates

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 13:41:49.241680

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not emit sequences.
    op.execute(sa.schema.CreateSequence(sa.Sequence("certificate_number_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("certificate_number", sa.Text(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("VALID", "EXPIRED", "REVOKED", name="certificate_status"),
            server_default="VALID",
            nullable=False,
        ),
        sa.Column("pdf_path", sa.Text(), nullable=False),
        sa.Column("data_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_certificates_application_id_applications"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("application_id", name=op.f("uq_certificates_application_id")),
        sa.UniqueConstraint("certificate_number", name=op.f("uq_certificates_certificate_number")),
        sa.UniqueConstraint("pdf_path", name=op.f("uq_certificates_pdf_path")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certificates")
    # ### end Alembic commands ###
    # Hand-written: autogenerate drops neither the sequence nor the enum type.
    op.execute(sa.schema.DropSequence(sa.Sequence("certificate_number_seq")))
    sa.Enum(name="certificate_status").drop(op.get_bind(), checkfirst=True)
