"""document review checklist

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 21:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not diff enum *values*, only enum existence. Same pattern
    # as 0005's `document_type` addition: adding a value to an existing type is its own
    # statement, safe inside this migration's transaction as long as the new value is never
    # *used* (inserted/defaulted/compared) within this same transaction — the new table below
    # only references `applications.id`, never `application_status`, so that holds here.
    # IF NOT EXISTS: the value survives `downgrade -1` (Postgres can't drop a single enum value,
    # see downgrade() below), so a repeat `upgrade head` must not fail on it.
    op.execute("ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'DOCUMENTS_DEFICIENT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_review_checklist_items",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("item_key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("checked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_document_review_checklist_items_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_review_checklist_items")),
        sa.UniqueConstraint(
            "application_id",
            "item_key",
            name=op.f("uq_document_review_checklist_items_application_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_review_checklist_items")
    # ### end Alembic commands ###
    # Postgres cannot drop a single enum value (no ALTER TYPE ... DROP VALUE). Recreating
    # application_status without DOCUMENTS_DEFICIENT would require rewriting every dependent
    # column (applications.status, application_status_history.from_status/to_status) and is out
    # of scope for an MVP downgrade path: the value is left in place, same documented limitation
    # as 0005's downgrade for `document_type`. `downgrade -1` after this revision does not fully
    # reverse the enum change.
