"""payments

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-01 00:11:05.160073

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Brand-new enum type (payment_status) created together with its owning table via a single
    # CREATE TABLE: SQLAlchemy auto-issues CREATE TYPE as a DDL event attached to Table.create()
    # when one of the table's own columns names a new Enum, exactly like 0001-0003's original enum
    # types (instrument_type, capacity_unit, ...) and 0006's own certificate_status. Unlike 0009's
    # verification_mode (a new type added onto an *existing* table via a bare add_column, which
    # needed an explicit VERIFICATION_MODE.create() first) or 0005/0008/0010 (ALTER TYPE ... ADD
    # VALUE on an *existing* type), this is the simplest case: a brand-new type, brand-new table,
    # nothing pre-existing to alter.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NOT_PAID", "PENDING", "PAID", name="payment_status"),
            server_default="NOT_PAID",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_payments_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("application_id", name=op.f("uq_payments_application_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # ### end Alembic commands ###
    # Hand-written: autogenerate/op.drop_table does not drop the enum type (same as 0002/0006).
    sa.Enum(name="payment_status").drop(op.get_bind(), checkfirst=True)
