"""Static region list.

Covers all 28 states + 8 union territories (36 total), using the standard 2-letter
vehicle-registration state codes (stable, not subject to the frequent district-boundary
reorganizations India's states have gone through in recent years), each with its full district
list.

ASSUMPTION: district *names and codes* here are a best-effort list compiled from the author's own
knowledge, not pulled from an official registry (e.g. the Census/LGD code list) and not re-checked
against one. District boundaries change often (splits, renames); this list may be missing recent
additions or carry a stale name for some districts. Jharkhand's DHN/RNC/BKR and Bihar's PAT codes
are pinned exactly as the demo data (`app/seed.py`, `instrument_uid` values already issued, and
most of the test suite) already depends on them — never change those four codes. Every other
district code is a short, non-standard abbreviation generated for this project only (not an
official code); verify against an authoritative source before any production use.
"""

from typing import TypedDict


class State(TypedDict):
    name: str
    districts: dict[str, str]


REGIONS: dict[str, State] = {
    "AP": {
        "name": "Andhra Pradesh",
        "districts": {
            "SRI": "Srikakulam",
            "PM": "Parvathipuram Manyam",
            "VIZ": "Vizianagaram",
            "VIS": "Visakhapatnam",
            "ASR": "Alluri Sitharama Raju",
            "ANA": "Anakapalli",
            "KAK": "Kakinada",
            "EG": "East Godavari",
            "KON": "Konaseema",
            "WG": "West Godavari",
            "ELU": "Eluru",
            "NTR": "NTR",
            "KRI": "Krishna",
            "GUN": "Guntur",
            "PAL": "Palnadu",
            "BAP": "Bapatla",
            "PRA": "Prakasam",
            "SN": "SPSR Nellore",
            "KUR": "Kurnool",
            "NAN": "Nandyal",
            "ANAN": "Anantapur",
            "SSS": "Sri Sathya Sai",
            "YK": "YSR Kadapa",
            "ANN": "Annamayya",
            "CHI": "Chittoor",
            "TIR": "Tirupati",
        },
    },
    "AR": {
        "name": "Arunachal Pradesh",
        "districts": {
            "TAW": "Tawang",
            "WK": "West Kameng",
            "EK": "East Kameng",
            "PAK": "Pakke-Kessang",
            "PP": "Papum Pare",
            "KK": "Kurung Kumey",
            "KD": "Kra Daadi",
            "LS": "Lower Subansiri",
            "US": "Upper Subansiri",
            "KAM": "Kamle",
            "LEP": "Leparada",
            "WS": "West Siang",
            "SY": "Shi Yomi",
            "UPSI": "Upper Siang",
            "ES": "East Siang",
            "SIA": "Siang",
            "LOSI": "Lower Siang",
            "LDV": "Lower Dibang Valley",
            "DV": "Dibang Valley",
            "ANJ": "Anjaw",
            "LOH": "Lohit",
            "NAM": "Namsai",
            "CHA": "Changlang",
            "TIR": "Tirap",
            "LON": "Longding",
        },
    },
    "AS": {
        "name": "Assam",
        "districts": {
            "BAK": "Baksa",
            "BAR": "Barpeta",
            "BIS": "Biswanath",
            "BON": "Bongaigaon",
            "CAC": "Cachar",
            "CHA": "Charaideo",
            "CHI": "Chirang",
            "DAR": "Darrang",
            "DHE": "Dhemaji",
            "DHU": "Dhubri",
            "DIB": "Dibrugarh",
            "DH": "Dima Hasao",
            "GOA": "Goalpara",
            "GOL": "Golaghat",
            "HAI": "Hailakandi",
            "HOJ": "Hojai",
            "JOR": "Jorhat",
            "KAM": "Kamrup",
            "KM": "Kamrup Metropolitan",
            "KA": "Karbi Anglong",
            "KAR": "Karimganj",
            "KOK": "Kokrajhar",
            "LAK": "Lakhimpur",
            "MAJ": "Majuli",
            "MOR": "Morigaon",
            "NAG": "Nagaon",
            "NAL": "Nalbari",
            "SIV": "Sivasagar",
            "SON": "Sonitpur",
            "SS": "South Salmara-Mankachar",
            "TAM": "Tamulpur",
            "TIN": "Tinsukia",
            "UDA": "Udalguri",
            "WKA": "West Karbi Anglong",
        },
    },
    "BR": {
        "name": "Bihar",
        "districts": {
            "PAT": "Patna",
            "ARA": "Araria",
            "ARW": "Arwal",
            "AUR": "Aurangabad",
            "BAN": "Banka",
            "BEG": "Begusarai",
            "BHA": "Bhagalpur",
            "BHO": "Bhojpur",
            "BUX": "Buxar",
            "DAR": "Darbhanga",
            "GAY": "Gaya",
            "GOP": "Gopalganj",
            "JAM": "Jamui",
            "JEH": "Jehanabad",
            "KAI": "Kaimur",
            "KAT": "Katihar",
            "KHA": "Khagaria",
            "KIS": "Kishanganj",
            "LAK": "Lakhisarai",
            "MAD": "Madhepura",
            "MADH": "Madhubani",
            "MUN": "Munger",
            "MUZ": "Muzaffarpur",
            "NAL": "Nalanda",
            "NAW": "Nawada",
            "PUR": "Purnia",
            "ROH": "Rohtas",
            "SAH": "Saharsa",
            "SAM": "Samastipur",
            "SAR": "Saran",
            "SHE": "Sheikhpura",
            "SHEO": "Sheohar",
            "SIT": "Sitamarhi",
            "SIW": "Siwan",
            "SUP": "Supaul",
            "VAI": "Vaishali",
            "WC": "West Champaran",
            "EC": "East Champaran",
        },
    },
    "CG": {
        "name": "Chhattisgarh",
        "districts": {
            "BAL": "Balod",
            "BB": "Baloda Bazar",
            "BALR": "Balrampur",
            "BAS": "Bastar",
            "BEM": "Bemetara",
            "BIJ": "Bijapur",
            "BIL": "Bilaspur",
            "DAN": "Dantewada",
            "DHA": "Dhamtari",
            "DUR": "Durg",
            "GAR": "Gariaband",
            "GAU": "Gaurela-Pendra-Marwahi",
            "JAN": "Janjgir-Champa",
            "JAS": "Jashpur",
            "KAB": "Kabirdham",
            "KAN": "Kanker",
            "KON": "Kondagaon",
            "KOR": "Korba",
            "KORI": "Koriya",
            "MAH": "Mahasamund",
            "MUN": "Mungeli",
            "NAR": "Narayanpur",
            "RAI": "Raigarh",
            "RAIP": "Raipur",
            "RAJ": "Rajnandgaon",
            "SUK": "Sukma",
            "SUR": "Surajpur",
            "SURG": "Surguja",
        },
    },
    "GA": {"name": "Goa", "districts": {"NG": "North Goa", "SG": "South Goa"}},
    "GJ": {
        "name": "Gujarat",
        "districts": {
            "AHM": "Ahmedabad",
            "AMR": "Amreli",
            "ANA": "Anand",
            "ARA": "Aravalli",
            "BAN": "Banaskantha",
            "BHA": "Bharuch",
            "BHAV": "Bhavnagar",
            "BOT": "Botad",
            "CU": "Chhota Udaipur",
            "DAH": "Dahod",
            "DAN": "Dang",
            "DD": "Devbhoomi Dwarka",
            "GAN": "Gandhinagar",
            "GS": "Gir Somnath",
            "JAM": "Jamnagar",
            "JUN": "Junagadh",
            "KHE": "Kheda",
            "KUT": "Kutch",
            "MAH": "Mahisagar",
            "MEH": "Mehsana",
            "MOR": "Morbi",
            "NAR": "Narmada",
            "NAV": "Navsari",
            "PAN": "Panchmahal",
            "PAT": "Patan",
            "POR": "Porbandar",
            "RAJ": "Rajkot",
            "SAB": "Sabarkantha",
            "SUR": "Surat",
            "SURE": "Surendranagar",
            "TAP": "Tapi",
            "VAD": "Vadodara",
            "VAL": "Valsad",
        },
    },
    "HR": {
        "name": "Haryana",
        "districts": {
            "AMB": "Ambala",
            "BHI": "Bhiwani",
            "CD": "Charkhi Dadri",
            "FAR": "Faridabad",
            "FAT": "Fatehabad",
            "GUR": "Gurugram",
            "HIS": "Hisar",
            "JHA": "Jhajjar",
            "JIN": "Jind",
            "KAI": "Kaithal",
            "KAR": "Karnal",
            "KUR": "Kurukshetra",
            "MAH": "Mahendragarh",
            "NUH": "Nuh",
            "PAL": "Palwal",
            "PAN": "Panchkula",
            "PANI": "Panipat",
            "REW": "Rewari",
            "ROH": "Rohtak",
            "SIR": "Sirsa",
            "SON": "Sonipat",
            "YAM": "Yamunanagar",
        },
    },
    "HP": {
        "name": "Himachal Pradesh",
        "districts": {
            "BIL": "Bilaspur",
            "CHA": "Chamba",
            "HAM": "Hamirpur",
            "KAN": "Kangra",
            "KIN": "Kinnaur",
            "KUL": "Kullu",
            "LAS": "Lahaul and Spiti",
            "MAN": "Mandi",
            "SHI": "Shimla",
            "SIR": "Sirmaur",
            "SOL": "Solan",
            "UNA": "Una",
        },
    },
    "JH": {
        "name": "Jharkhand",
        "districts": {
            "DHN": "Dhanbad",
            "RNC": "Ranchi",
            "BKR": "Bokaro",
            "CHA": "Chatra",
            "DEO": "Deoghar",
            "DUM": "Dumka",
            "ES": "East Singhbhum",
            "GAR": "Garhwa",
            "GIR": "Giridih",
            "GOD": "Godda",
            "GUM": "Gumla",
            "HAZ": "Hazaribagh",
            "JAM": "Jamtara",
            "KHU": "Khunti",
            "KOD": "Koderma",
            "LAT": "Latehar",
            "LOH": "Lohardaga",
            "PAK": "Pakur",
            "PAL": "Palamu",
            "RAM": "Ramgarh",
            "SAH": "Sahebganj",
            "SK": "Seraikela Kharsawan",
            "SIM": "Simdega",
            "WS": "West Singhbhum",
        },
    },
    "KA": {
        "name": "Karnataka",
        "districts": {
            "BAG": "Bagalkot",
            "BAL": "Ballari",
            "BEL": "Belagavi",
            "BR": "Bengaluru Rural",
            "BU": "Bengaluru Urban",
            "BID": "Bidar",
            "CHA": "Chamarajanagar",
            "CHI": "Chikkaballapur",
            "CHIK": "Chikkamagaluru",
            "CHIT": "Chitradurga",
            "DK": "Dakshina Kannada",
            "DAV": "Davanagere",
            "DHA": "Dharwad",
            "GAD": "Gadag",
            "HAS": "Hassan",
            "HAV": "Haveri",
            "KAL": "Kalaburagi",
            "KOD": "Kodagu",
            "KOL": "Kolar",
            "KOP": "Koppal",
            "MAN": "Mandya",
            "MYS": "Mysuru",
            "RAI": "Raichur",
            "RAM": "Ramanagara",
            "SHI": "Shivamogga",
            "TUM": "Tumakuru",
            "UDU": "Udupi",
            "UK": "Uttara Kannada",
            "VIJ": "Vijayapura",
            "YAD": "Yadgir",
            "VIJA": "Vijayanagara",
        },
    },
    "KL": {
        "name": "Kerala",
        "districts": {
            "ALA": "Alappuzha",
            "ERN": "Ernakulam",
            "IDU": "Idukki",
            "KAN": "Kannur",
            "KAS": "Kasaragod",
            "KOL": "Kollam",
            "KOT": "Kottayam",
            "KOZ": "Kozhikode",
            "MAL": "Malappuram",
            "PAL": "Palakkad",
            "PAT": "Pathanamthitta",
            "THI": "Thiruvananthapuram",
            "THR": "Thrissur",
            "WAY": "Wayanad",
        },
    },
    "MP": {
        "name": "Madhya Pradesh",
        "districts": {
            "AM": "Agar Malwa",
            "ALI": "Alirajpur",
            "ANU": "Anuppur",
            "ASH": "Ashoknagar",
            "BAL": "Balaghat",
            "BAR": "Barwani",
            "BET": "Betul",
            "BHI": "Bhind",
            "BHO": "Bhopal",
            "BUR": "Burhanpur",
            "CHH": "Chhatarpur",
            "CHHI": "Chhindwara",
            "DAM": "Damoh",
            "DAT": "Datia",
            "DEW": "Dewas",
            "DHA": "Dhar",
            "DIN": "Dindori",
            "GUN": "Guna",
            "GWA": "Gwalior",
            "HAR": "Harda",
            "NAR": "Narmadapuram",
            "IND": "Indore",
            "JAB": "Jabalpur",
            "JHA": "Jhabua",
            "KAT": "Katni",
            "KHA": "Khandwa",
            "KHAR": "Khargone",
            "MAN": "Mandla",
            "MAND": "Mandsaur",
            "MOR": "Morena",
            "NARS": "Narsinghpur",
            "NEE": "Neemuch",
            "NIW": "Niwari",
            "PAN": "Panna",
            "RAI": "Raisen",
            "RAJ": "Rajgarh",
            "RAT": "Ratlam",
            "REW": "Rewa",
            "SAG": "Sagar",
            "SAT": "Satna",
            "SEH": "Sehore",
            "SEO": "Seoni",
            "SHA": "Shahdol",
            "SHAJ": "Shajapur",
            "SHE": "Sheopur",
            "SHI": "Shivpuri",
            "SID": "Sidhi",
            "SIN": "Singrauli",
            "TIK": "Tikamgarh",
            "UJJ": "Ujjain",
            "UMA": "Umaria",
            "VID": "Vidisha",
        },
    },
    "MH": {
        "name": "Maharashtra",
        "districts": {
            "AHM": "Ahmednagar",
            "AKO": "Akola",
            "AMR": "Amravati",
            "CS": "Chhatrapati Sambhajinagar",
            "BEE": "Beed",
            "BHA": "Bhandara",
            "BUL": "Buldhana",
            "CHA": "Chandrapur",
            "DHU": "Dhule",
            "GAD": "Gadchiroli",
            "GON": "Gondia",
            "HIN": "Hingoli",
            "JAL": "Jalgaon",
            "JALN": "Jalna",
            "KOL": "Kolhapur",
            "LAT": "Latur",
            "MC": "Mumbai City",
            "MS": "Mumbai Suburban",
            "NAG": "Nagpur",
            "NAN": "Nanded",
            "NAND": "Nandurbar",
            "NAS": "Nashik",
            "DHA": "Dharashiv",
            "PAL": "Palghar",
            "PAR": "Parbhani",
            "PUN": "Pune",
            "RAI": "Raigad",
            "RAT": "Ratnagiri",
            "SAN": "Sangli",
            "SAT": "Satara",
            "SIN": "Sindhudurg",
            "SOL": "Solapur",
            "THA": "Thane",
            "WAR": "Wardha",
            "WAS": "Washim",
            "YAV": "Yavatmal",
        },
    },
    "MN": {
        "name": "Manipur",
        "districts": {
            "BIS": "Bishnupur",
            "CHA": "Chandel",
            "CHU": "Churachandpur",
            "IE": "Imphal East",
            "IW": "Imphal West",
            "JIR": "Jiribam",
            "KAK": "Kakching",
            "KAM": "Kamjong",
            "KAN": "Kangpokpi",
            "NON": "Noney",
            "PHE": "Pherzawl",
            "SEN": "Senapati",
            "TAM": "Tamenglong",
            "TEN": "Tengnoupal",
            "THO": "Thoubal",
            "UKH": "Ukhrul",
        },
    },
    "ML": {
        "name": "Meghalaya",
        "districts": {
            "EGH": "East Garo Hills",
            "EJH": "East Jaintia Hills",
            "EKH": "East Khasi Hills",
            "EWKH": "Eastern West Khasi Hills",
            "NGH": "North Garo Hills",
            "RB": "Ri Bhoi",
            "SGH": "South Garo Hills",
            "SWGH": "South West Garo Hills",
            "SWKH": "South West Khasi Hills",
            "WGH": "West Garo Hills",
            "WJH": "West Jaintia Hills",
            "WKH": "West Khasi Hills",
        },
    },
    "MZ": {
        "name": "Mizoram",
        "districts": {
            "AIZ": "Aizawl",
            "CHA": "Champhai",
            "HNA": "Hnahthial",
            "KHA": "Khawzawl",
            "KOL": "Kolasib",
            "LAW": "Lawngtlai",
            "LUN": "Lunglei",
            "MAM": "Mamit",
            "SAI": "Saiha",
            "SAIT": "Saitual",
            "SER": "Serchhip",
        },
    },
    "NL": {
        "name": "Nagaland",
        "districts": {
            "CHU": "Chumoukedima",
            "DIM": "Dimapur",
            "KIP": "Kiphire",
            "KOH": "Kohima",
            "LON": "Longleng",
            "MOK": "Mokokchung",
            "MON": "Mon",
            "NIU": "Niuland",
            "NOK": "Noklak",
            "PER": "Peren",
            "PHE": "Phek",
            "SHA": "Shamator",
            "TSE": "Tseminyu",
            "TUE": "Tuensang",
            "WOK": "Wokha",
            "ZUN": "Zunheboto",
        },
    },
    "OD": {
        "name": "Odisha",
        "districts": {
            "ANG": "Angul",
            "BAL": "Balangir",
            "BALA": "Balasore",
            "BAR": "Bargarh",
            "BHA": "Bhadrak",
            "BOU": "Boudh",
            "CUT": "Cuttack",
            "DEO": "Deogarh",
            "DHE": "Dhenkanal",
            "GAJ": "Gajapati",
            "GAN": "Ganjam",
            "JAG": "Jagatsinghpur",
            "JAJ": "Jajpur",
            "JHA": "Jharsuguda",
            "KAL": "Kalahandi",
            "KAN": "Kandhamal",
            "KEN": "Kendrapara",
            "KEND": "Kendujhar",
            "KHO": "Khordha",
            "KOR": "Koraput",
            "MAL": "Malkangiri",
            "MAY": "Mayurbhanj",
            "NAB": "Nabarangpur",
            "NAY": "Nayagarh",
            "NUA": "Nuapada",
            "PUR": "Puri",
            "RAY": "Rayagada",
            "SAM": "Sambalpur",
            "SUB": "Subarnapur",
            "SUN": "Sundargarh",
        },
    },
    "PB": {
        "name": "Punjab",
        "districts": {
            "AMR": "Amritsar",
            "BAR": "Barnala",
            "BAT": "Bathinda",
            "FAR": "Faridkot",
            "FS": "Fatehgarh Sahib",
            "FAZ": "Fazilka",
            "FER": "Ferozepur",
            "GUR": "Gurdaspur",
            "HOS": "Hoshiarpur",
            "JAL": "Jalandhar",
            "KAP": "Kapurthala",
            "LUD": "Ludhiana",
            "MAL": "Malerkotla",
            "MAN": "Mansa",
            "MOG": "Moga",
            "MUK": "Muktsar",
            "PAT": "Pathankot",
            "PATI": "Patiala",
            "RUP": "Rupnagar",
            "SASN": "Sahibzada Ajit Singh Nagar",
            "SAN": "Sangrur",
            "SBSN": "Shaheed Bhagat Singh Nagar",
            "TT": "Tarn Taran",
        },
    },
    "RJ": {
        "name": "Rajasthan",
        "districts": {
            "AJM": "Ajmer",
            "ALW": "Alwar",
            "BAN": "Banswara",
            "BAR": "Baran",
            "BARM": "Barmer",
            "BHA": "Bharatpur",
            "BHI": "Bhilwara",
            "BIK": "Bikaner",
            "BUN": "Bundi",
            "CHI": "Chittorgarh",
            "CHU": "Churu",
            "DAU": "Dausa",
            "DHO": "Dholpur",
            "DUN": "Dungarpur",
            "HAN": "Hanumangarh",
            "JAI": "Jaipur",
            "JAIS": "Jaisalmer",
            "JAL": "Jalore",
            "JHA": "Jhalawar",
            "JHU": "Jhunjhunu",
            "JOD": "Jodhpur",
            "KAR": "Karauli",
            "KOT": "Kota",
            "NAG": "Nagaur",
            "PAL": "Pali",
            "PRA": "Pratapgarh",
            "RAJ": "Rajsamand",
            "SM": "Sawai Madhopur",
            "SIK": "Sikar",
            "SIR": "Sirohi",
            "SG": "Sri Ganganagar",
            "TON": "Tonk",
            "UDA": "Udaipur",
        },
    },
    "SK": {
        "name": "Sikkim",
        "districts": {
            "GAN": "Gangtok",
            "GYA": "Gyalshing",
            "MAN": "Mangan",
            "NAM": "Namchi",
            "PAK": "Pakyong",
            "SOR": "Soreng",
        },
    },
    "TN": {
        "name": "Tamil Nadu",
        "districts": {
            "ARI": "Ariyalur",
            "CHE": "Chengalpattu",
            "CHEN": "Chennai",
            "COI": "Coimbatore",
            "CUD": "Cuddalore",
            "DHA": "Dharmapuri",
            "DIN": "Dindigul",
            "ERO": "Erode",
            "KAL": "Kallakurichi",
            "KAN": "Kanchipuram",
            "KANY": "Kanyakumari",
            "KAR": "Karur",
            "KRI": "Krishnagiri",
            "MAD": "Madurai",
            "MAY": "Mayiladuthurai",
            "NAG": "Nagapattinam",
            "NAM": "Namakkal",
            "NIL": "Nilgiris",
            "PER": "Perambalur",
            "PUD": "Pudukkottai",
            "RAM": "Ramanathapuram",
            "RAN": "Ranipet",
            "SAL": "Salem",
            "SIV": "Sivaganga",
            "TEN": "Tenkasi",
            "THA": "Thanjavur",
            "THE": "Theni",
            "THO": "Thoothukudi",
            "TIR": "Tiruchirappalli",
            "TIRU": "Tirunelveli",
            "TI": "Tirupathur",
            "IRUP": "Tiruppur",
            "IRUV": "Tiruvallur",
            "RUVA": "Tiruvannamalai",
            "UVAR": "Tiruvarur",
            "VEL": "Vellore",
            "VIL": "Viluppuram",
            "VIR": "Virudhunagar",
        },
    },
    "TS": {
        "name": "Telangana",
        "districts": {
            "ADI": "Adilabad",
            "BK": "Bhadradri Kothagudem",
            "HYD": "Hyderabad",
            "JAG": "Jagtial",
            "JAN": "Jangaon",
            "JB": "Jayashankar Bhupalpally",
            "JG": "Jogulamba Gadwal",
            "KAM": "Kamareddy",
            "KAR": "Karimnagar",
            "KHA": "Khammam",
            "KB": "Komaram Bheem",
            "MAH": "Mahabubabad",
            "MAHA": "Mahabubnagar",
            "MAN": "Mancherial",
            "MED": "Medak",
            "MEDC": "Medchal-Malkajgiri",
            "MUL": "Mulugu",
            "NAG": "Nagarkurnool",
            "NAL": "Nalgonda",
            "NAR": "Narayanpet",
            "NIR": "Nirmal",
            "NIZ": "Nizamabad",
            "PED": "Peddapalli",
            "RS": "Rajanna Sircilla",
            "RAN": "Rangareddy",
            "SAN": "Sangareddy",
            "SID": "Siddipet",
            "SUR": "Suryapet",
            "VIK": "Vikarabad",
            "WAN": "Wanaparthy",
            "WAR": "Warangal",
            "HAN": "Hanumakonda",
            "YB": "Yadadri Bhuvanagiri",
        },
    },
    "TR": {
        "name": "Tripura",
        "districts": {
            "DHA": "Dhalai",
            "GOM": "Gomati",
            "KHO": "Khowai",
            "NT": "North Tripura",
            "SEP": "Sepahijala",
            "ST": "South Tripura",
            "UNA": "Unakoti",
            "WT": "West Tripura",
        },
    },
    "UP": {
        "name": "Uttar Pradesh",
        "districts": {
            "AGR": "Agra",
            "ALI": "Aligarh",
            "AN": "Ambedkar Nagar",
            "AME": "Amethi",
            "AMR": "Amroha",
            "AUR": "Auraiya",
            "AYO": "Ayodhya",
            "AZA": "Azamgarh",
            "BAG": "Baghpat",
            "BAH": "Bahraich",
            "BAL": "Ballia",
            "BALR": "Balrampur",
            "BAN": "Banda",
            "BAR": "Barabanki",
            "BARE": "Bareilly",
            "BAS": "Basti",
            "BHA": "Bhadohi",
            "BIJ": "Bijnor",
            "BUD": "Budaun",
            "BUL": "Bulandshahr",
            "CHA": "Chandauli",
            "CHI": "Chitrakoot",
            "DEO": "Deoria",
            "ETA": "Etah",
            "ETAW": "Etawah",
            "FAR": "Farrukhabad",
            "FAT": "Fatehpur",
            "FIR": "Firozabad",
            "GBN": "Gautam Buddha Nagar",
            "GHA": "Ghaziabad",
            "GHAZ": "Ghazipur",
            "GON": "Gonda",
            "GOR": "Gorakhpur",
            "HAM": "Hamirpur",
            "HAP": "Hapur",
            "HAR": "Hardoi",
            "HAT": "Hathras",
            "JAL": "Jalaun",
            "JAU": "Jaunpur",
            "JHA": "Jhansi",
            "KAN": "Kannauj",
            "KD": "Kanpur Dehat",
            "KN": "Kanpur Nagar",
            "KAS": "Kasganj",
            "KAU": "Kaushambi",
            "KHE": "Kheri",
            "KUS": "Kushinagar",
            "LAL": "Lalitpur",
            "LUC": "Lucknow",
            "MAH": "Maharajganj",
            "MAHO": "Mahoba",
            "MAI": "Mainpuri",
            "MAT": "Mathura",
            "MAU": "Mau",
            "MEE": "Meerut",
            "MIR": "Mirzapur",
            "MOR": "Moradabad",
            "MUZ": "Muzaffarnagar",
            "PIL": "Pilibhit",
            "PRA": "Pratapgarh",
            "PRAY": "Prayagraj",
            "RAE": "Raebareli",
            "RAM": "Rampur",
            "SAH": "Saharanpur",
            "SAM": "Sambhal",
            "SKN": "Sant Kabir Nagar",
            "SHA": "Shahjahanpur",
            "SHAM": "Shamli",
            "SHR": "Shravasti",
            "SID": "Siddharthnagar",
            "SIT": "Sitapur",
            "SON": "Sonbhadra",
            "SUL": "Sultanpur",
            "UNN": "Unnao",
            "VAR": "Varanasi",
        },
    },
    "UK": {
        "name": "Uttarakhand",
        "districts": {
            "ALM": "Almora",
            "BAG": "Bageshwar",
            "CHA": "Chamoli",
            "CHAM": "Champawat",
            "DEH": "Dehradun",
            "HAR": "Haridwar",
            "NAI": "Nainital",
            "PG": "Pauri Garhwal",
            "PIT": "Pithoragarh",
            "RUD": "Rudraprayag",
            "TG": "Tehri Garhwal",
            "USN": "Udham Singh Nagar",
            "UTT": "Uttarkashi",
        },
    },
    "WB": {
        "name": "West Bengal",
        "districts": {
            "ALI": "Alipurduar",
            "BAN": "Bankura",
            "BIR": "Birbhum",
            "CB": "Cooch Behar",
            "DD": "Dakshin Dinajpur",
            "DAR": "Darjeeling",
            "HOO": "Hooghly",
            "HOW": "Howrah",
            "JAL": "Jalpaiguri",
            "JHA": "Jhargram",
            "KAL": "Kalimpong",
            "KOL": "Kolkata",
            "MAL": "Malda",
            "MUR": "Murshidabad",
            "NAD": "Nadia",
            "NP": "North 24 Parganas",
            "PB": "Paschim Bardhaman",
            "PM": "Paschim Medinipur",
            "PUBA": "Purba Bardhaman",
            "PUME": "Purba Medinipur",
            "PUR": "Purulia",
            "SP": "South 24 Parganas",
            "UD": "Uttar Dinajpur",
        },
    },
    "AN": {
        "name": "Andaman and Nicobar Islands",
        "districts": {"NIC": "Nicobar", "NAMA": "North and Middle Andaman", "SA": "South Andaman"},
    },
    "CH": {"name": "Chandigarh", "districts": {"CHA": "Chandigarh"}},
    "DN": {
        "name": "Dadra and Nagar Haveli and Daman and Diu",
        "districts": {"DANH": "Dadra and Nagar Haveli", "DAM": "Daman", "DIU": "Diu"},
    },
    "DL": {
        "name": "Delhi",
        "districts": {
            "CD": "Central Delhi",
            "ED": "East Delhi",
            "ND": "New Delhi",
            "NODE": "North Delhi",
            "NED": "North East Delhi",
            "NWD": "North West Delhi",
            "SHA": "Shahdara",
            "SD": "South Delhi",
            "SED": "South East Delhi",
            "SWD": "South West Delhi",
            "WD": "West Delhi",
        },
    },
    "JK": {
        "name": "Jammu and Kashmir",
        "districts": {
            "ANA": "Anantnag",
            "BAN": "Bandipora",
            "BAR": "Baramulla",
            "BUD": "Budgam",
            "DOD": "Doda",
            "GAN": "Ganderbal",
            "JAM": "Jammu",
            "KAT": "Kathua",
            "KIS": "Kishtwar",
            "KUL": "Kulgam",
            "KUP": "Kupwara",
            "POO": "Poonch",
            "PUL": "Pulwama",
            "RAJ": "Rajouri",
            "RAM": "Ramban",
            "REA": "Reasi",
            "SAM": "Samba",
            "SHO": "Shopian",
            "SRI": "Srinagar",
            "UDH": "Udhampur",
        },
    },
    "LA": {"name": "Ladakh", "districts": {"KAR": "Kargil", "LEH": "Leh"}},
    "LD": {"name": "Lakshadweep", "districts": {"LAK": "Lakshadweep"}},
    "PY": {
        "name": "Puducherry",
        "districts": {"KAR": "Karaikal", "MAH": "Mahe", "PUD": "Puducherry", "YAN": "Yanam"},
    },
}


def is_valid_state(state_code: str | None) -> bool:
    return state_code in REGIONS


def is_valid_region(state_code: str | None, district_code: str | None) -> bool:
    state = REGIONS.get(state_code or "")
    return state is not None and district_code in state["districts"]
